### ISSUE TITLE
Generated routes are relative to project root

### ISSUE THREAD

**Issue by yangshun** [triyanox/next-routes#1]
Hey there, trying to use this project but the routes seem to be generated relative to the root directory instead of the app directory. Not sure if I'm doing something wrongly here.

```js
export const routes = {
  "src/app/[locale]/auth/password-reset": {
    "path": "src/app/[locale]/auth/password-reset",
    "params": {
      "locale": ""
    },
    "isDynamic": true
  },
  "src/app/[locale]/auth/password-reset-sent": {
    "path": "src/app/[locale]/auth/password-reset-sent",
    "params": {
      "locale": ""
    },
    "isDynamic": true
  },
  "src/app/[locale]/auth/unverified": {
    "path": "src/app/[locale]/auth/unverified",
    "params": {
      "locale": ""
    },
    "isDynamic": true
  },
  ...
```

My director structure is

```
src
  app
    [locale]
      foo
      bar
package.json
next.config.js
```

**Comment by chaqchase** [comment]
Hey @yangshun ! If you are using `src` directory the default options will work for you just fine if you want to customize the behavior or you have a deferent project setup  you can try using the second argument of the plugin in the `next.config.js` something like this

```ts
import withRoutes from "@triyanox/next-routes";
import { cwd } from "process";

/** @type {import("next").NextConfig} */
const config = withRoutes(
  {},
  {
    appDir: `${cwd()}/src/app`,
    // ...other options
  },
);
```

Thank you @yangshun  for opening this issue I will leave it open for now let me know if the fix worked for you !

**Comment by chaqchase** [comment]
Hey @yangshun I have published a new version with updated docs for simpler use the previous one didn't include an indication that all the paths are relative to the root directory.
Thank you for opening this issue much appreciated !
